"""``infra/db/init/002_skills.sql`` must stay isomorphic with the taxonomy module.

``docs/DATABASE.md`` §6 states it as a requirement — *"技能词典 由 infra/db/init/002_skills.sql
与 packages/ai/.../parsing/skill_taxonomy.py 双源同构，CI 断言两者一致"* — and this is
that assertion. The file is generated by ``scripts/gen_skills_sql.py``; this test parses
it back so a hand-edit (or a forgotten regeneration) fails the build instead of shipping
a Docker deployment whose skill dictionary differs from the one the matcher uses.

The parse is deliberately strict: it reads the ``INSERT ... VALUES`` rows and compares
canonical ids, display names, categories and alias arrays, in order.
"""

from __future__ import annotations

import json
from pathlib import Path
import re

from careerforge_ai.parsing.skill_taxonomy import SKILLS, TAXONOMY_VERSION

REPO_ROOT = Path(__file__).resolve().parents[3]
SKILLS_SQL = REPO_ROOT / "infra" / "db" / "init" / "002_skills.sql"
EXTENSIONS_SQL = REPO_ROOT / "infra" / "db" / "init" / "001_extensions.sql"

_ROW_RE = re.compile(
    r"\(\s*gen_random_uuid\(\),\s*"
    r"'(?P<canonical_id>(?:[^']|'')*)',\s*"
    r"'(?P<display_name>(?:[^']|'')*)',\s*"
    r"'(?P<category>[a-z]+)',\s*"
    r"'(?P<aliases>\[.*?\])'::jsonb",
    re.DOTALL,
)


def _rows() -> list[dict[str, object]]:
    text = SKILLS_SQL.read_text(encoding="utf-8")
    rows: list[dict[str, object]] = []
    for match in _ROW_RE.finditer(text):
        rows.append(
            {
                "canonical_id": match.group("canonical_id").replace("''", "'"),
                "display_name": match.group("display_name").replace("''", "'"),
                "category": match.group("category"),
                "aliases": json.loads(match.group("aliases")),
            }
        )
    return rows


def test_skills_sql_exists_and_declares_the_taxonomy_version() -> None:
    assert SKILLS_SQL.exists(), "infra/db/init/002_skills.sql is missing"
    header = SKILLS_SQL.read_text(encoding="utf-8")[:1200]
    assert TAXONOMY_VERSION in header
    assert str(len(SKILLS)) in header
    assert "GENERATED FILE" in header


def test_skills_sql_rows_match_the_taxonomy_exactly() -> None:
    rows = _rows()
    assert len(rows) == len(SKILLS) == 126

    for row, skill in zip(rows, SKILLS, strict=True):
        assert row["canonical_id"] == skill.canonical_id
        assert row["display_name"] == skill.display_name
        assert row["category"] == skill.category.value
        assert row["aliases"] == list(skill.aliases)


def test_skills_sql_is_idempotent_on_replay() -> None:
    """The init script re-runs on `docker compose run migrate`; it must upsert."""
    text = SKILLS_SQL.read_text(encoding="utf-8")
    assert "ON CONFLICT (canonical_id) DO UPDATE" in text


def test_extensions_sql_enables_pgcrypto_and_vector() -> None:
    text = EXTENSIONS_SQL.read_text(encoding="utf-8")
    assert "CREATE EXTENSION IF NOT EXISTS pgcrypto" in text
    assert "CREATE EXTENSION IF NOT EXISTS vector" in text
