"""CareerForge AI structured-output contracts.

Every LLM interaction in this project is bounded by one of these schemas.
String parsing of model output does not exist anywhere in the codebase — if a
response does not validate, the step fails, retries once with a repair prompt,
and then degrades. That is the structural half of the anti-hallucination story.
"""

from __future__ import annotations

from careerforge_ai.schemas.claim import (
    ClaimLLMVerdict,
    ClaimReason,
    ClaimSource,
    ClaimValidation,
    ClaimValidationRequest,
    ExtractedClaim,
    NumericMention,
    ResumeBullet,
    ResumeIntegrity,
    ResumeOptimizationResult,
    SafeRewrite,
)
from careerforge_ai.schemas.common import (
    AgentRunStatus,
    ApplicationStatus,
    CacheKind,
    ClaimRuleCode,
    ClaimStatus,
    Confidence,
    DegradationReason,
    DifficultyLevel,
    EvidenceKind,
    EvidenceRelation,
    EvidenceStrength,
    GapLevel,
    GraphNodeType,
    InterviewMode,
    InterviewStatus,
    Origin,
    RequirementLevel,
    RetrievalChannel,
    Score0to100,
    SkillCategory,
    SkillLevel,
    SourceAuthority,
    Unit,
    utcnow,
)
from careerforge_ai.schemas.evidence import (
    ConfidenceBreakdown,
    ConfidenceInputs,
    EvidenceCandidate,
    EvidenceGraph,
    EvidenceItem,
    EvidenceLink,
    EvidenceLocator,
    GraphEdge,
    GraphNode,
    GraphQuery,
    RetrievalHit,
    RetrievalResult,
)
from careerforge_ai.schemas.github import (
    CommitSummary,
    EngineeringSignal,
    ExtractedProjectIntelligence,
    GithubProfileAnalysis,
    LanguageStat,
    ProjectIntelligence,
    RepoFileSummary,
    RepoSummary,
)
from careerforge_ai.schemas.interview import (
    DifficultyChange,
    EvidenceConflict,
    ExtractedQuestion,
    ExtractedTurnEvaluation,
    InterviewPlanItem,
    InterviewScorecard,
    InterviewSession,
    InterviewTurn,
    QuestionReview,
    ScorecardDimension,
    TurnEvaluation,
)
from careerforge_ai.schemas.job import (
    ExtractedJD,
    ExtractedJDSkill,
    JDAnalysis,
    JDSkill,
    JDSkillNode,
    JDSkillTree,
    JobSummary,
    SkillGapMatrix,
    SkillGapRow,
)
from careerforge_ai.schemas.learning import (
    ExtractedLearningPlan,
    ExtractedLearningWeek,
    ExtractedMiniProject,
    LearningPlan,
    LearningPlanWeek,
    MiniProject,
)
from careerforge_ai.schemas.match import (
    JobMatchResult,
    MatchDimension,
    MatchDimensionKey,
    MatchedSkill,
    MatchWhy,
    MissedSkill,
    UnknownSkill,
)
from careerforge_ai.schemas.observability import (
    AgentRunRecord,
    CacheStats,
    Cost,
    CostByGroup,
    ExtractedRunNarrative,
    ProviderSelection,
    StepTrace,
    TokenUsage,
)
from careerforge_ai.schemas.profile import (
    Achievement,
    CandidateProfile,
    Education,
    Experience,
    ExtractedAchievement,
    ExtractedEducation,
    ExtractedExperience,
    ExtractedProfile,
    ExtractedProject,
    ProfileImportResult,
    ProfileSkill,
    ProfileStrength,
    ProfileStrengthDimension,
    Project,
    SkillRef,
)
from careerforge_ai.schemas.public import (
    ExtractedRecruiterSummary,
    PublicEvidenceLink,
    PublicProfileSummary,
    PublicProject,
    PublicSectionVisibility,
    PublicSkill,
)

__all__ = [
    # common
    "AgentRunStatus",
    "ApplicationStatus",
    "CacheKind",
    "ClaimRuleCode",
    "ClaimStatus",
    "Confidence",
    "DegradationReason",
    "DifficultyLevel",
    "EvidenceKind",
    "EvidenceRelation",
    "EvidenceStrength",
    "GapLevel",
    "GraphNodeType",
    "InterviewMode",
    "InterviewStatus",
    "Origin",
    "RequirementLevel",
    "RetrievalChannel",
    "Score0to100",
    "SkillCategory",
    "SkillLevel",
    "SourceAuthority",
    "Unit",
    "utcnow",
    # evidence
    "ConfidenceBreakdown",
    "ConfidenceInputs",
    "EvidenceCandidate",
    "EvidenceGraph",
    "EvidenceItem",
    "EvidenceLink",
    "EvidenceLocator",
    "GraphEdge",
    "GraphNode",
    "GraphQuery",
    "RetrievalHit",
    "RetrievalResult",
    # profile
    "Achievement",
    "CandidateProfile",
    "Education",
    "Experience",
    "ExtractedAchievement",
    "ExtractedEducation",
    "ExtractedExperience",
    "ExtractedProfile",
    "ExtractedRecruiterSummary",
    "ExtractedProject",
    "ProfileImportResult",
    "ProfileSkill",
    "ProfileStrength",
    "PublicEvidenceLink",
    "PublicProfileSummary",
    "PublicProject",
    "PublicSectionVisibility",
    "PublicSkill",
    "ProfileStrengthDimension",
    "Project",
    "SkillRef",
    # job
    "ExtractedJD",
    "ExtractedJDSkill",
    "JDAnalysis",
    "JDSkill",
    "JDSkillNode",
    "JDSkillTree",
    "JobSummary",
    "SkillGapMatrix",
    "SkillGapRow",
    # match
    "JobMatchResult",
    "MatchDimension",
    "MatchDimensionKey",
    "MatchedSkill",
    "MatchWhy",
    "MissedSkill",
    "UnknownSkill",
    # claim
    "ClaimLLMVerdict",
    "ClaimReason",
    "ClaimSource",
    "ClaimValidation",
    "ClaimValidationRequest",
    "ExtractedClaim",
    "NumericMention",
    "ResumeBullet",
    "ResumeIntegrity",
    "ResumeOptimizationResult",
    "SafeRewrite",
    # interview
    "DifficultyChange",
    "EvidenceConflict",
    "ExtractedQuestion",
    "ExtractedTurnEvaluation",
    "InterviewPlanItem",
    "InterviewScorecard",
    "InterviewSession",
    "InterviewTurn",
    "QuestionReview",
    "ScorecardDimension",
    "TurnEvaluation",
    # learning
    "ExtractedLearningPlan",
    "ExtractedLearningWeek",
    "ExtractedMiniProject",
    "LearningPlan",
    "LearningPlanWeek",
    "MiniProject",
    # github
    "CommitSummary",
    "EngineeringSignal",
    "ExtractedProjectIntelligence",
    "GithubProfileAnalysis",
    "LanguageStat",
    "ProjectIntelligence",
    "RepoFileSummary",
    "RepoSummary",
    # observability
    "AgentRunRecord",
    "CacheStats",
    "Cost",
    "CostByGroup",
    "ExtractedRunNarrative",
    "ProviderSelection",
    "StepTrace",
    "TokenUsage",
]
