"""Synchronise the ``skills`` taxonomy from the AI core into the database.

The controlled vocabulary lives in code
(:mod:`careerforge_ai.parsing.skill_taxonomy`) because that is what the matcher,
the parser and the evidence attribution all consult at runtime; the ``skills`` table
is the queryable mirror that lets a future endpoint join ``profile_skills`` against
it. ``docs/DATABASE.md`` §6 requires the two to stay isomorphic, and asserts it in
CI through ``infra/db/init/002_skills.sql`` (generated by ``scripts/gen_skills_sql.py``)
and ``tests/test_skill_taxonomy.py``.

The sync is an upsert keyed on ``canonical_id``: renaming a display name or adding
an alias updates the row, and a skill removed from the taxonomy is deactivated
rather than deleted, because user rows may already reference it and a manual
correction should survive a taxonomy edit.
"""

from __future__ import annotations

from dataclasses import dataclass, field

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from careerforge_ai.parsing.skill_taxonomy import SKILLS, TAXONOMY_VERSION, Skill
from careerforge_api.models.skill import Skill as SkillRow

__all__ = ["SkillSyncReport", "sync_skill_taxonomy", "taxonomy_entries"]


@dataclass(slots=True)
class SkillSyncReport:
    """What a :meth:`sync_skill_taxonomy` run changed."""

    inserted: int = 0
    updated: int = 0
    deactivated: int = 0
    unchanged: int = 0
    total: int = 0
    taxonomy_version: str = TAXONOMY_VERSION
    categories: dict[str, int] = field(default_factory=dict)

    def as_dict(self) -> dict[str, object]:
        return {
            "inserted": self.inserted,
            "updated": self.updated,
            "deactivated": self.deactivated,
            "unchanged": self.unchanged,
            "total": self.total,
            "taxonomyVersion": self.taxonomy_version,
            "categories": self.categories,
        }


def taxonomy_entries() -> tuple[Skill, ...]:
    """The canonical skill list, in declaration order."""
    return SKILLS


async def sync_skill_taxonomy(
    session: AsyncSession,
    *,
    prune: bool = False,
) -> SkillSyncReport:
    """Idempotently mirror the taxonomy into ``skills``."""
    report = SkillSyncReport()
    existing = {
        row.canonical_id: row for row in (await session.execute(select(SkillRow))).scalars()
    }
    report.total = len(SKILLS)

    for skill in SKILLS:
        report.categories[skill.category.value] = report.categories.get(skill.category.value, 0) + 1
        aliases = list(skill.aliases)
        row = existing.pop(skill.canonical_id, None)
        if row is None:
            session.add(
                SkillRow(
                    canonical_id=skill.canonical_id,
                    display_name=skill.display_name,
                    category=skill.category.value,
                    aliases=aliases,
                    is_active=True,
                )
            )
            report.inserted += 1
            continue

        changed = False
        if row.display_name != skill.display_name:
            row.display_name = skill.display_name
            changed = True
        if row.category != skill.category.value:
            row.category = skill.category.value
            changed = True
        if list(row.aliases or []) != aliases:
            row.aliases = aliases
            changed = True
        if not row.is_active:
            row.is_active = True
            changed = True
        if changed:
            report.updated += 1
        else:
            report.unchanged += 1

    if prune:
        # Skills that left the taxonomy are retired, never deleted: existing
        # profile_skills rows must keep resolving to a readable label.
        for row in existing.values():
            if row.is_active:
                row.is_active = False
                report.deactivated += 1

    await session.flush()
    return report
