-- CareerForge AI - skill taxonomy seed (PostgreSQL).
--
-- GENERATED FILE - DO NOT EDIT BY HAND.
--   regenerate:  python scripts/gen_skills_sql.py
--   verify:      python scripts/gen_skills_sql.py --check
--
-- Source of truth: packages/ai/careerforge_ai/parsing/skill_taxonomy.py
-- (docs/DATABASE.md section 6 requires the two to stay isomorphic; the API mirrors the
-- same list into the `skills` table at startup through skill_taxonomy_service, and
-- apps/api/tests/test_skills_sql.py parses this file to keep it honest.)
--
-- taxonomy version: taxonomy@1.0.0
-- skill count:      126
--
-- Executed by the postgres container on first initialisation
-- (docker-compose mounts infra/db/init as /docker-entrypoint-initdb.d).

INSERT INTO skills (id, canonical_id, display_name, category, aliases, is_active, created_at, updated_at)
VALUES
    (gen_random_uuid(), 'c', 'C', 'language', '["c language", "ansi c", "c99", "c11"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'cplusplus', 'C++', 'language', '["cpp", "c++11", "c++14", "c++17", "c++20"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'csharp', 'C#', 'language', '["csharp", ".net c#"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'python', 'Python', 'language', '["python3", "py"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'java', 'Java', 'language', '[]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'javascript', 'JavaScript', 'language', '["js", "es6", "ecmascript"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'typescript', 'TypeScript', 'language', '["ts"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'go', 'Go', 'language', '["golang"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'rust', 'Rust', 'language', '[]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'kotlin', 'Kotlin', 'language', '[]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'swift', 'Swift', 'language', '[]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'matlab', 'MATLAB', 'language', '["matlab/simulink"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'verilog', 'Verilog', 'language', '["systemverilog", "vhdl"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'assembly', 'Assembly', 'language', '["asm", "arm assembly"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'sql', 'SQL', 'language', '[]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'bash', 'Bash', 'language', '["shell", "shell script", "shellscript"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'lua', 'Lua', 'language', '[]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'stm32', 'STM32', 'embedded', '["stm32f1", "stm32f4", "stm32f7", "stm32h7", "stm32f407", "stm32 hal", "hal库"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'free_rtos', 'FreeRTOS', 'embedded', '["freertos", "free rtos", "rtos"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'rt_thread', 'RT-Thread', 'embedded', '["rtthread"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'zephyr', 'Zephyr', 'embedded', '["zephyr rtos"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'embedded_linux', 'Embedded Linux', 'embedded', '["嵌入式linux", "yocto", "buildroot"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'linux_driver', 'Linux Driver', 'embedded', '["字符设备驱动", "kernel module", "内核驱动"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'device_driver', 'Device Driver', 'embedded', '["驱动开发", "外设驱动"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'esp32', 'ESP32', 'embedded', '["esp-idf", "espressif"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'arduino', 'Arduino', 'embedded', '[]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'raspberry_pi', 'Raspberry Pi', 'embedded', '["树莓派"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'cuda_mcu', 'MCU', 'embedded', '["microcontroller", "单片机", "mcu开发"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'dsp', 'DSP', 'embedded', '["数字信号处理", "digital signal processing"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'fpga', 'FPGA', 'embedded', '["zynq", "xilinx", "altera"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'pcb', 'PCB Design', 'embedded', '["pcb设计", "altium", "立创eda", "easyeda"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'uart', 'UART', 'embedded', '["usart", "串口", "serial port"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'spi', 'SPI', 'embedded', '[]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'i2c', 'I2C', 'embedded', '["iic", "i²c"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'can', 'CAN', 'embedded', '["can bus", "canopen", "can总线", "canfd", "can fd"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'modbus', 'Modbus', 'embedded', '["modbus rtu", "modbus tcp"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'usb', 'USB', 'embedded', '["usb device", "usb hid"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'ethernet', 'Ethernet', 'embedded', '["以太网", "lwip"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'bluetooth', 'Bluetooth', 'embedded', '["ble", "低功耗蓝牙"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'mqtt', 'MQTT', 'embedded', '["mqtts"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'pwm', 'PWM', 'embedded', '["pwm输出"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'adc', 'ADC', 'embedded', '["dac", "模数转换"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'dma', 'DMA', 'embedded', '["dma传输", "dma搬运"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'interrupt', 'Interrupt Handling', 'embedded', '["中断", "isr", "中断服务程序"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'pid', 'PID Control', 'embedded', '["pid控制", "pid算法", "闭环控制"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'motor_control', 'Motor Control', 'embedded', '["电机控制", "foc", "bldc", "步进电机", "直流电机"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'imu', 'IMU', 'embedded', '["mpu6050", "icm20602", "惯性测量单元", "加速度计"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'encoder', 'Encoder', 'embedded', '["编码器", "霍尔传感器"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'sensor_fusion', 'Sensor Fusion', 'embedded', '["姿态解算", "attitude estimation", "卡尔曼滤波", "kalman filter", "互补滤波"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'autosar', 'AUTOSAR', 'embedded', '["autosar classic"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'bootloader', 'Bootloader', 'embedded', '["iap", "固件升级", "ota"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'low_power', 'Low Power Design', 'embedded', '["低功耗", "sleep mode"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'rtos_scheduler', 'RTOS Scheduling', 'embedded', '["任务调度", "优先级反转", "priority inversion"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'ros', 'ROS', 'domain', '["ros2", "robot operating system"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'px4', 'PX4', 'domain', '["px4 autopilot"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'ardupilot', 'ArduPilot', 'domain', '["apm"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'slam', 'SLAM', 'ai', '["建图定位", "cartographer"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'path_planning', 'Path Planning', 'domain', '["路径规划", "a*", "rrt"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'computer_vision', 'Computer Vision', 'ai', '["opencv", "机器视觉", "图像处理"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'control_theory', 'Control Theory', 'domain', '["自动控制", "状态空间", "lqr", "mpc"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'fastapi', 'FastAPI', 'backend', '["fast api"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'django', 'Django', 'backend', '["drf", "django rest framework"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'flask', 'Flask', 'backend', '[]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'spring_boot', 'Spring Boot', 'backend', '["spring", "springboot"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'nodejs', 'Node.js', 'backend', '["node", "nodejs", "express", "nestjs"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'grpc', 'gRPC', 'backend', '["protobuf", "protocol buffers"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'rest_api', 'REST API', 'backend', '["restful", "rest 接口", "http api"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'microservices', 'Microservices', 'backend', '["微服务"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'redis', 'Redis', 'database', '["redis cluster"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'kafka', 'Kafka', 'backend', '["消息队列", "message queue", "rabbitmq", "rocketmq"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'celery', 'Celery', 'backend', '["异步任务", "task queue"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'websocket', 'WebSocket', 'backend', '[]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'sqlalchemy', 'SQLAlchemy', 'backend', '["orm"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'postgresql', 'PostgreSQL', 'database', '["postgres", "pg", "pgvector"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'mysql', 'MySQL', 'database', '["mariadb"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'sqlite', 'SQLite', 'database', '[]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'mongodb', 'MongoDB', 'database', '["mongo"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'elasticsearch', 'Elasticsearch', 'database', '["es", "opensearch"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'vector_db', 'Vector Database', 'ai', '["faiss", "chroma", "milvus", "qdrant", "向量数据库"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'react', 'React', 'frontend', '["react.js", "reactjs"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'nextjs', 'Next.js', 'frontend', '["next", "nextjs"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'vue', 'Vue', 'frontend', '["vue.js", "vue3", "nuxt"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'tailwind', 'Tailwind CSS', 'frontend', '["tailwindcss"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'html_css', 'HTML/CSS', 'frontend', '["html", "css", "scss", "less"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'vite', 'Vite', 'frontend', '["webpack", "构建工具"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'electron', 'Electron', 'frontend', '["tauri"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'miniprogram', 'Mini Program', 'frontend', '["小程序", "微信小程序", "uniapp"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'pytorch', 'PyTorch', 'ai', '["torch"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'tensorflow', 'TensorFlow', 'ai', '["tf", "keras"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'llm', 'LLM', 'ai', '["大模型", "large language model"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'rag', 'RAG', 'ai', '["retrieval augmented generation", "检索增强生成"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'langchain', 'LangChain', 'ai', '["langgraph", "llamaindex"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'prompt_engineering', 'Prompt Engineering', 'ai', '["提示工程", "prompt 设计"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'fine_tuning', 'Fine-tuning', 'ai', '["微调", "lora", "qlora", "sft"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'agent', 'AI Agent', 'ai', '["智能体", "multi-agent", "agent 编排"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'numpy_pandas', 'NumPy/Pandas', 'ai', '["numpy", "pandas", "scipy", "数据分析"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'sklearn', 'scikit-learn', 'ai', '["sklearn", "机器学习"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'deep_learning', 'Deep Learning', 'ai', '["深度学习", "神经网络", "cnn", "transformer"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'nlp', 'NLP', 'ai', '["自然语言处理"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'mlops', 'MLOps', 'ai', '["模型部署", "model serving", "vllm", "onnx"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'docker', 'Docker', 'devops', '["docker compose", "容器化", "container"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'kubernetes', 'Kubernetes', 'devops', '["k8s", "k3s"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'cicd', 'CI/CD', 'devops', '["github actions", "jenkins", "gitlab ci", "持续集成"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'linux', 'Linux', 'devops', '["ubuntu", "centos", "linux 系统"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'nginx', 'Nginx', 'devops', '["反向代理", "reverse proxy"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'terraform', 'Terraform', 'devops', '["iac"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'monitoring', 'Monitoring', 'devops', '["prometheus", "grafana", "监控告警"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'git', 'Git', 'tool', '["github", "gitlab", "版本控制"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'cmake', 'CMake', 'tool', '["makefile", "构建系统"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'gdb', 'GDB', 'tool', '["调试器", "jlink", "stlink", "仿真器"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'oscilloscope', 'Oscilloscope', 'tool', '["示波器", "逻辑分析仪", "logic analyzer"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'keil', 'Keil MDK', 'tool', '["keil5", "mdk"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'cubemx', 'STM32CubeMX', 'tool', '["cubemx", "cubeide", "stm32cubeide"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'matlab_simulink', 'Simulink', 'tool', '["simulink 仿真"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'swagger', 'OpenAPI', 'tool', '["swagger", "接口文档"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'unity_engine', 'Unity', 'tool', '["ue", "unreal"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'system_design', 'System Design', 'domain', '["系统设计", "架构设计"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'performance_tuning', 'Performance Tuning', 'domain', '["性能优化", "性能调优", "profiling"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'code_review', 'Code Review', 'domain', '["代码评审"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'unit_testing', 'Unit Testing', 'domain', '["单元测试", "pytest", "gtest", "junit"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'agile', 'Agile', 'soft', '["scrum", "敏捷开发"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'technical_writing', 'Technical Writing', 'soft', '["技术文档", "文档撰写"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'communication', 'Communication', 'soft', '["沟通协作", "团队协作"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'problem_solving', 'Problem Solving', 'soft', '["问题解决", "故障排查", "debugging"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'project_management', 'Project Management', 'soft', '["项目管理", "需求分析"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'english', 'English', 'soft', '["英语", "cet-6", "cet6"]'::jsonb, true, now(), now())
ON CONFLICT (canonical_id) DO UPDATE SET
    display_name = EXCLUDED.display_name,
    category     = EXCLUDED.category,
    aliases      = EXCLUDED.aliases,
    is_active    = true,
    updated_at   = now();
